version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - deploy_network
    container_name: backend
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8080
  streamlit:
    build: ./frontend/
    ports:
      - "8501:8501"
    networks:
      - deploy_network
    container_name: frontend
    command: streamlit run ui.py --server.port 8501
  redis:
   image: "redis/redis-stack"
   build: .
   ports:
     - "6379:6379"
   networks:
     - deploy_network
   container_name: redis
   command: Redis-server
networks:
  deploy_network:
    driver: bridge